/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as GalleryRouteImport } from './routes/gallery'
import { Route as DietPlannerRouteImport } from './routes/diet-planner'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as ClassesRouteImport } from './routes/classes'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminScannerRouteImport } from './routes/admin.scanner'

const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryRoute = GalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const DietPlannerRoute = DietPlannerRouteImport.update({
  id: '/diet-planner',
  path: '/diet-planner',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const ClassesRoute = ClassesRouteImport.update({
  id: '/classes',
  path: '/classes',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminScannerRoute = AdminScannerRouteImport.update({
  id: '/admin/scanner',
  path: '/admin/scanner',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/classes': typeof ClassesRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRoute
  '/diet-planner': typeof DietPlannerRoute
  '/gallery': typeof GalleryRoute
  '/pricing': typeof PricingRoute
  '/admin/scanner': typeof AdminScannerRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/classes': typeof ClassesRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRoute
  '/diet-planner': typeof DietPlannerRoute
  '/gallery': typeof GalleryRoute
  '/pricing': typeof PricingRoute
  '/admin/scanner': typeof AdminScannerRoute
  '/admin': typeof AdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/classes': typeof ClassesRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRoute
  '/diet-planner': typeof DietPlannerRoute
  '/gallery': typeof GalleryRoute
  '/pricing': typeof PricingRoute
  '/admin/scanner': typeof AdminScannerRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/auth'
    | '/classes'
    | '/contact'
    | '/dashboard'
    | '/diet-planner'
    | '/gallery'
    | '/pricing'
    | '/admin/scanner'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/auth'
    | '/classes'
    | '/contact'
    | '/dashboard'
    | '/diet-planner'
    | '/gallery'
    | '/pricing'
    | '/admin/scanner'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/auth'
    | '/classes'
    | '/contact'
    | '/dashboard'
    | '/diet-planner'
    | '/gallery'
    | '/pricing'
    | '/admin/scanner'
    | '/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AuthRoute: typeof AuthRoute
  ClassesRoute: typeof ClassesRoute
  ContactRoute: typeof ContactRoute
  DashboardRoute: typeof DashboardRoute
  DietPlannerRoute: typeof DietPlannerRoute
  GalleryRoute: typeof GalleryRoute
  PricingRoute: typeof PricingRoute
  AdminScannerRoute: typeof AdminScannerRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery': {
      id: '/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof GalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/diet-planner': {
      id: '/diet-planner'
      path: '/diet-planner'
      fullPath: '/diet-planner'
      preLoaderRoute: typeof DietPlannerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/classes': {
      id: '/classes'
      path: '/classes'
      fullPath: '/classes'
      preLoaderRoute: typeof ClassesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/scanner': {
      id: '/admin/scanner'
      path: '/admin/scanner'
      fullPath: '/admin/scanner'
      preLoaderRoute: typeof AdminScannerRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AuthRoute: AuthRoute,
  ClassesRoute: ClassesRoute,
  ContactRoute: ContactRoute,
  DashboardRoute: DashboardRoute,
  DietPlannerRoute: DietPlannerRoute,
  GalleryRoute: GalleryRoute,
  PricingRoute: PricingRoute,
  AdminScannerRoute: AdminScannerRoute,
  AdminIndexRoute: AdminIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
